= Person Component
:sourcedir: ../

When the Person component is first rendered, it has no `data`, so it simply returns `null`.

It has a useEffect hook that will asyncronously run a fetch using the imported PERSON_QUERY.

Once the fetch returns, it will update the `data` state, so there is something to render.

Since the state has changed it will now be re-rendered based on the new state.

This time it will render a section element containing a

* h2 element with the persons displayname
* an img element with a picture of the person
* a paragraph with the person's dateofbirth
* a smart RichText component, which is able to render images, links and macros.

Notice that the RichText is imported from the `@enonic/react-components` npm module.

The RichText component comes with some basic `default components` for images, links and macros.

Depending upon how your web application is `hosted` the urls generated by the `default components` may be wrong, which is why you can create your own `Image` and `Link` components and pass those to the RichText component.

In addition the RichText component, doesn't really know how macros are supposed to look, so it's `default Macro component` will simply show a placeholder.

The next chapters will cover our custom implementation of the `Image`, `Link` and `Macro` components.

.src/main/resources/components/Person.tsx
[source, TypeScript]
----
include::{sourcedir}src/main/resources/static/components/Person.tsx[]
----

== Navigation

In the next chapter you will learn about the RichText <<image#,Image>> Component.
