= Person Component
:sourcedir: ../

== Query

Similarly to person list component, let's create `src/queries/person.ts` file with a query:

.src/queries/person.ts
[source,graphql]
----
include::{sourcedir}src/main/resources/static/queries/person.ts[]
----

== Component

Next, let's define Person component in the `src/components/Person.tsx` file:

.src/components/Person.tsx
[source, TypeScript]
----
include::{sourcedir}src/main/resources/static/components/PersonWithoutExtensions.tsx[]
----

NOTE: Notice that we used `RichText` component from `@enonic/react-components` npm module to render the HTML area `bio` field.
More about it in the <<rich-text#,next chapter>>.

Lastly, we need to create `RestProps` interface in the `src/components/index.d.ts` file:

.src/components/index.d.ts
[source,TypeScript]
----
include::{sourcedir}src/main/resources/static/components/index.d.ts[]
----

We'll cover what it does in detail in the <<rich-text#,next chapter>>.

== Styling

We are going to use https://www.reacttutorial.com/css-modules-react[css modules^] to style the macro:

Create a `Person.module.css` file with the following content:

.src/components/Person.module.css
[source,css]
----
include::{sourcedir}src/main/resources/static/components/Person.module.css[]
----

== Routing

Finally, we need to update the App.tsx file to include the `Person` component and display it on  `/p/:name/:personId` route:

.src/App.tsx
[source,TypeScript]
----
import './App.sass';

import {Route, BrowserRouter as Router, Routes, } from 'react-router-dom';

import {PersonList} from './components/PersonList';
import {Person} from './components/Person';

export default function App() {
  return (
    <Router>
      <Routes>
        <Route path="/" element={<PersonList />}/>
        <Route path="/p/:name/:personId" element={<Person />}/>
        <Route path='*' element={<p>URL doesn't exist!</p>}/>
      </Routes>
    </Router>
  );
}
----

To see the `Person` component in action, open http://localhost:3000[] and click any of the persons.
Alternatively, here's the direct link to http://localhost:3000/p/lea-seydoux/a8b374a2-c532-45eb-9aa1-73d1c37cd681[Lea Seydoux^].

== Next step

Learn how to customize <<rich-text#,Rich text>> component.
