= Person Component
:sourcedir: ../

When the Person component is first rendered, it has no `data`, so it simply returns `null`.

It has a useEffect hook that will asyncronously run a fetch using the imported PERSON_QUERY.

Once the fetch returns, it will update the `data` state, so there is something to render.

Since the state has changed it will now be re-rendered based on the new state.

This time it will render a section element containing a

* h2 element with the persons displayname
* an img element with a picture of the person
* a paragraph with the person's dateofbirth
* a smart RichText component, which is able to render images, links and macros.

Notice that the RichText is imported from the `@enonic/react-components` npm module.

The RichText component comes with some basic `default components` for images, links and macros.

Depending upon how your web application is `hosted` the urls generated by the `default components` may be wrong, which is why you can create your own `Image` and `Link` components and pass those to the RichText component.

In addition, the RichText component doesn't really know how macros are supposed to look, so it's `default Macro component` will simply show a placeholder.

We will cover custom implementation of the `Image`, `Link` and `Macro` components in the following chapters.

== Query

First, let's create `src/queries/person.gql` file with a query that we want to execute to fetch the data:

.src/queries/person.gql
[source,graphql]
----
include::{sourcedir}src/main/resources/static/queries/person.ts[]
----

== Component

Next, let's define Person component in the `src/components/Person.tsx` file:

.src/components/Person.tsx
[source, TypeScript]
----
include::{sourcedir}src/main/resources/static/components/Person.tsx[]
----

IMPORTANT: We used `RichText` component from `@enonic/react-components` npm module to render the HTML area `bio` field.
It will take care of rendering images, links and macros.

Similarly to `PersonList` component, we are passing `guillotineUrl` as a property to this component.

== RestProps

Let's define the `RestProps` type in the `src/components/index.ts` file:

.src/components/index.d.ts
[source,TypeScript]
----
include::{sourcedir}src/main/resources/static/components/index.d.ts[]
----

This file defines properties `guillotineUrl` and `personId` that we want to add to the `RichText` component as parameters:

[source,TypeScript]
----
<RichText<RestProps>
  ...
  guillotineUrl={guillotineUrl}
  personId={personId}
  ...
/>
----

== Update App.tsx

Finally, we need to update the App.tsx file to include the `Person` component and display it on  `/p/:name/:personId` route.

.src/App.tsx
[source,TypeScript]
----
import './App.sass';

import {Route, BrowserRouter as Router, Routes, } from 'react-router-dom';

import {PersonList} from './components/PersonList';
import {Person} from './components/Person';

export default function App({guillotineUrl = '/site/intro/master'}: { guillotineUrl?: string }) {
  return (
    <Router>
      <Routes>
        <Route path="/" element={<PersonList guillotineUrl={guillotineUrl}/>}/>
        <Route
          element={<Person guillotineUrl={guillotineUrl}/>}
          path="/p/:name/:personId"
        />
        <Route path='*' element={<p>URL doesn't exist!</p>}/>
      </Routes>
    </Router>
  );
}
----

To see the `Person` component in action, open http://localhost:3000 and click any of the person.
Alternatively, here's the direct link to http://localhost:3000/p/brad-pitt/3a7b833f-3c37-4d55-88ae-cea21c556c68[Brad Pitt].

== Next step

Learn how to make custom RichText <<image#,Image>> component.
