= Person Component
:sourcedir: ../

When the Person component is first rendered, it has no `data`, so it simply returns `null`.

It has a useEffect hook that will asyncronously run a fetch using the imported PERSON_QUERY.

Once the fetch returns, it will update the `data` state, so there is something to render.

Since the state has changed it will now be re-rendered based on the new state.

This time it will render a section element containing a

* h2 element with the persons displayname
* an img element with a picture of the person
* a paragraph with the person's dateofbirth
* a smart RichText component, which is able to render images, links and macros.

Notice that the RichText is imported from the `@enonic/react-components` npm module.

The RichText component comes with some basic `default components` for images, links and macros.

Depending upon how your web application is `hosted` the urls generated by the `default components` may be wrong, which is why you can create your own `Image` and `Link` components and pass those to the RichText component.

In addition, the RichText component doesn't really know how macros are supposed to look, so it's `default Macro component` will simply show a placeholder.

We will cover custom implementation of the `Image`, `Link` and `Macro` components in the following chapters.

== Query

First, let's create `src/queries/person.gql` file with a query that we want to execute to fetch the data:

.src/queries/person.gql
[source,graphql]
----
include::{sourcedir}src/main/resources/static/queries/person.gql[]
----

== Component

Next, let's define Person component in the `src/components/Person.tsx` file:

.src/components/Person.tsx
[source, TypeScript]
----
import type {RichTextData} from '@enonic/react-components';
import type {RestProps} from '.';
import type {Element} from 'html-react-parser';


import {forceArray} from '@enonic/js-utils/array/forceArray';
import {RichText} from '@enonic/react-components';
import {ElementType} from 'domelementtype';
import React, {
  useEffect,
  useState,
} from 'react';
import {
  Link as RouterLink,
  useParams,
} from 'react-router-dom';
// import {Image} from '../components/Image';
// import {Link} from '../components/Link';
// import {Macro} from '../components/Macro';
// eslint-disable-next-line import/no-webpack-loader-syntax
import PERSON_QUERY from '!!raw-loader!../queries/person.gql';


export function Person({
  guillotineUrl,
}: {
  guillotineUrl: string
}) {
  const {
    // name,
    personId = ''
  } = useParams();
  const [data, setData] = useState<{
    _name: string
    data: {
      bio: RichTextData
      dateofbirth: string
      photos: {
        imageUrl: string
      }[]
    }
    displayName: string
  }>();

  useEffect(() => {
    fetch(guillotineUrl, {
      body: JSON.stringify({
        query: PERSON_QUERY,
        variables: {
          personId,
        }
      }),
      headers: { // HTTP/2 uses lowercase header keys
        'content-type': 'application/json'
      },
      method: 'POST',
    })
      .then(response => response.json())
      .then(json => {
        const value = json.data.guillotine.get;
        setData(value)
      });
  }, []); // useEffect

  if (!data) {
    return null;
  }

  const {
    data: {
      bio,
      dateofbirth,
      photos
    },
    displayName
  } = data;
  const imageSrc = photos ? forceArray(photos)[0].imageUrl : undefined;

  return (
    <section>
      <h2>{displayName}</h2>
      <img src={imageSrc} alt={displayName}/>
      <p>{dateofbirth}</p>
      <RichText<RestProps>
        replacer={(el: Element, data: RichTextData) => {
          if (
            el.name === 'p'
            && el.children[0].type === ElementType.Text
            && el.children[0].data === 'Some text'
          ) {
            return <p>Replaced text</p>;
          }
        }}
        data={bio}
        // Image={Image}
        // Link={Link}
        // Macro={Macro}
        guillotineUrl={guillotineUrl}
        personId={personId}
        tag='article'
      />
      <RouterLink to='/'>Back to list</RouterLink>
    </section>
  );
}
----

IMPORTANT: We used `RichText` component from `@enonic/react-components` npm module to render the HTML area `bio` field.
It will take care of rendering images, links and macros.

NOTE: Again, notice the `import PERSON_QUERY from '!!raw-loader!../queries/person.gql';` line.
This syntax instructs webpack to load the file as a raw string.

Similarly to `PersonList` component, we are passing `guillotineUrl` as a property to this component.

== RestProps

Let's define the `RestProps` type in the `src/components/index.ts` file:

.src/components/index.d.ts
[source,TypeScript]
----
include::{sourcedir}src/main/resources/static/components/index.d.ts[]
----

This file defines properties `guillotineUrl` and `personId` that we want to add to the `RichText` component as parameters:

[source,TypeScript]
----
<RichText<RestProps>
  ...
  guillotineUrl={guillotineUrl}
  personId={personId}
  ...
/>
----

== Update App.tsx

Finally, we need to update the App.tsx file to include the `Person` component and display it on  `/p/:name/:personId` route.

.src/App.tsx
[source,TypeScript]
----
import './App.sass';

import {Route, BrowserRouter as Router, Routes, } from 'react-router-dom';

import {PersonList} from './components/PersonList';
import {Person} from './components/Person';

export default function App({guillotineUrl = '/site/intro/master'}: { guillotineUrl?: string }) {
  return (
    <Router>
      <Routes>
        <Route path="/" element={<PersonList guillotineUrl={guillotineUrl}/>}/>
        <Route
          element={<Person guillotineUrl={guillotineUrl}/>}
          path="/p/:name/:personId"
        />
        <Route path='*' element={<p>URL doesn't exist!</p>}/>
      </Routes>
    </Router>
  );
}
----

To see the `Person` component in action, open http://localhost:3000 and click any of the person.
Alternatively, here's the direct link to http://localhost:3000/p/brad-pitt/3a7b833f-3c37-4d55-88ae-cea21c556c68[Brad Pitt].

== Next step

Learn how to make custom RichText <<image#,Image>> component.
