= Query
:sourcedir: ../

Before we even write a single line of code, lets have a look at the data we're going to be working with:

== Data

In the previous chapter we installed the `Enonic intro` app. On installation it created a project name `intro` within the Enonic XP instance. If you open this project in Content Studio you will see that it contains a number of content types and content. In this tutorial we are going to use the `Person` content items and corresponding `images` it provides.


== Query Playground

In the previous chapter we installed the `Guillotine` app. This app provides a query playground where you can try out various queries.

== Query a list of persons

In order to test the query below you first have to open the `intro` project in Content Studio, then open the `Query Playground` panel and paste the query below into the query editor.

.src/main/resources/static/queries/personListQuery.ts
[source, TypeScript]
----
include::{sourcedir}src/main/resources/static/queries/personListQuery.ts[]
----

== Get data about a specific person

In order to test the query below you first have to open the `intro` project in Content Studio, then open the `Query Playground` panel and paste the query below into the query editor.

In addition you need to set a query variable in the Query Playground Variables panel:
[source, json]
----
{
  "personId": "a8b374a2-c532-45eb-9aa1-73d1c37cd681"
}
----

.src/main/resources/static/queries/personQuery.ts
[source, TypeScript]
----
include::{sourcedir}src/main/resources/static/queries/personQuery.ts[]
----
