:sourcedir: ../
:imagesdir: media/

= Rich text

The RichText component is able to render html area fields and comes with basic components for images, links and macros that can be customized.

Depending upon how your web application is `hosted` the urls generated by the `default components` may be wrong, which is why you can create your own `Image` and `Link` components and pass those to the RichText component.

In addition, the RichText component doesn't really know how macros are supposed to look, so it's `default Macro component` will simply show a placeholder.

== Passing additional params

You can pass additional params to the RichText component by specifying them in the generic type, in this case `RestProps`:

[source,TypeScript]
----
<RichText<RestProps>
  ...
  guillotineUrl={guillotineUrl}
  personId={personId}
  ...
/>
----

Where `RestProps` is defined in the `src/components/index.ts` file and declares the additional properties:

.src/components/index.d.ts
[source,TypeScript]
----
include::{sourcedir}src/main/resources/static/components/index.d.ts[]
----

